Fix missing tile entity registration
attempt to fix error:

```java
[23:17:20] [Server thread/ERROR] [FML]: A TileEntity type com.bioxx.tfc.TileEntities.TECrucible has throw an exception trying to write state. It will not persist. Report this to the mod author
java.lang.RuntimeException: class com.bioxx.tfc.TileEntities.TECrucible is missing a mapping! This is a bug!
        at net.minecraft.tileentity.TileEntity.func_145841_b(TileEntity.java:80) ~[aor.class:?]
        at com.bioxx.tfc.TileEntities.TECrucible.func_145841_b(TECrucible.java:41) ~[TECrucible.class:?]
        at net.minecraft.world.chunk.storage.AnvilChunkLoader.func_75820_a(AnvilChunkLoader.java:370) [aqk.class:?]
        at net.minecraft.world.chunk.storage.AnvilChunkLoader.func_75816_a(AnvilChunkLoader.java:197) [aqk.class:?]
        at net.minecraft.world.gen.ChunkProviderServer.func_73242_b(ChunkProviderServer.java:256) [ms.class:?]
        at net.minecraft.world.gen.ChunkProviderServer.func_73151_a(ChunkProviderServer.java:302) [ms.class:?]
        at net.minecraft.world.WorldServer.func_73044_a(WorldServer.java:809) [mt.class:?]
        at net.minecraft.server.MinecraftServer.func_71267_a(MinecraftServer.java:318) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:569) [MinecraftServer.class:?]
        at fastcraft.u.a(F:289) [fastcraft-1.25.jar:?]
        at fastcraft.H.aq(F:36) [fastcraft-1.25.jar:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:396) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [li.class:?]
```